src/objects/maica_cc__Support_Category__c.object
<CustomObject>
</CustomObject>

src/objects/maica_cc__Support_Item__c.object
<CustomObject>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>Indicates if the Product is the Bucket, or Category Level, Product for the related Support
            Category
        </description>
        <formula>Id = Support_Category__r.Category_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates if the Product is the Bucket, or Category Level, Product for the related Support
            Category
        </inlineHelpText>
        <label>Bucket</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_Number__c</fullName>
        <formula>Support_Category__r.maica_cc__Category_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Favourite__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This represents a Product that is commonly used within Service Delivery so will be displayed as
            a priority in the NDIS Product Management console.
        </inlineHelpText>
        <label>Favourite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Day__c</fullName>
        <label>Service Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Time__c</fullName>
        <label>Service Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daytime</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Night</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Support Category associated with this Product.</description>
        <label>Support Category</label>
        <referenceTo>maica_cc__Support_Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Item_Number__c</fullName>
        <description>Unique NDIS Reference Number derived from Support Category, Sequence Number, Registration Group,
            Outcome Domain and Support Purpose
        </description>
        <externalId>true</externalId>
        <inlineHelpText>Unique NDIS Reference Number derived from Support Category, Sequence Number, Registration Group,
            Outcome Domain and Support Purpose
        </inlineHelpText>
        <label>Support Item Number</label>
        <length>55</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/NDISProductManagGetAvailableItemsProc.cls
//SECURED!
public with sharing class NDISProductManagGetAvailableItemsProc extends AbstractProcessor {

    private List<PricebookEntry> items;
    private final Integer limitVar = 10;

    public override Response process(Request request) {
        this.request = request;

        this.retrieveItems();

        return this.response;
    }

    private void retrieveItems() {
        fflib_QueryFactory queryFactory = new fflib_QueryFactory(PricebookEntry.SObjectType);
        queryFactory.selectFields(('Id,' +
                'UnitPrice,' +
                'Product2Id,' +
                'Product2.Id,' +
                'Product2.Name,' +
                'Product2.QuantityUnitOfMeasure,' +
                'Product2.Bucket__c,' +
                'Product2.Support_Category__c,' +
                'Product2.Support_Category__r.Name,' +
                'Product2.Support_Category__r.maica_cc__Category_Number__c,' +
                'Product2.Support_Category__r.maica_cc__Support_Purpose__c,' +
                'Product2.Support_Category__r.maica_cc__Short_Name__c,' +
                'Product2.Support_Item_Number__c,' +
                'Product2.Service_Day__c,' +
                'Product2.Service_Time__c,' +
                'Product2.Favourite__c').split(','));

        String supportCategoryId = this.request.getString('filter.supportCategoryId');
        String supportItemName = this.request.getString('filter.supportItemName');
        String pricebookId = this.request.getRequiredString('filter.pricebookId');
        String serviceDay = this.request.getRequiredString('filter.serviceDay');
        String serviceTime = this.request.getString('filter.serviceTime');
        String activePlanId = this.request.getString('filter.activePlanId');
        Boolean isEnforceActivePlan = this.request.getBoolean('filter.isEnforceActivePlan') == true && String.isNotBlank(activePlanId);
        Boolean isCategoryProduct = this.request.getBoolean('filter.isCategoryProduct') == true;

        List<String> conditions = new List<String>{
                'Pricebook2Id = :pricebookId',
                'Product2.Support_Category__r.maica_cc__Support_Purpose__c != \'Subsidy\'',
                'Product2.Support_Category__r.maica_cc__Support_Purpose__c != \'Supplement\'',
                'Product2.Support_Category__r.maica_cc__Support_Purpose__c != \'Claimable Fee\'',
                'Product2.Support_Category__r.maica_cc__Support_Purpose__c != \'Billable Fee\'',
                'Product2.Support_Category__r.maica_cc__Support_Purpose__c != \'Client Contribution\''
        };

        if (isCategoryProduct == true) {
            conditions.add('Product2.Bucket__c = true');
        } else {

            conditions.add('Product2.Bucket__c != true');

            if (String.isNotBlank(serviceDay)) {
                List<String> serviceDays = new List<String>{
                        null, serviceDay
                };
                conditions.add('Product2.Service_Day__c IN :serviceDays');
            }

            if (String.isNotBlank(serviceTime)) {
                List<String> serviceTimes = new List<String>{
                        null, serviceTime
                };
                conditions.add('Product2.Service_Time__c IN :serviceTimes');
            }

            if (String.isNotBlank(supportItemName)) {
                supportItemName = '%' + supportItemName + '%';
                conditions.add('(Product2.Name LIKE :supportItemName OR Product2.Support_Item_Number__c LIKE :supportItemName)');
            }
        }

        if (String.isNotBlank(supportCategoryId)) {
            conditions.add('Product2.Support_Category__c = :supportCategoryId');
        }

        Set<String> categoryIds = new Set<String>();
        Map<String, maica_cc__Funding_Item__c> budgetMap;
        Map<String, Decimal> remainingAmountBySupportCategory = new Map<String, Decimal>();

        if (isEnforceActivePlan == true) {
            List<maica_cc__Funding_Item__c> planBudgets = [
                    SELECT Id, Name, maica_cc__Support_Category__c, maica_cc__Support_Category__r.maica_cc__Support_Purpose__c, maica_cc__Support_Item__c
                    FROM maica_cc__Funding_Item__c
                    WHERE maica_cc__Funding__c = :activePlanId
                    WITH USER_MODE
            ];

            List<AggregateResult> coreRemainingResults = [
                    SELECT SUM(maica_cc__Remaining_Amount__c) Remaining_Amount__c
                    FROM maica_cc__Funding_Item__c
                    WHERE maica_cc__Funding__c = :activePlanId AND maica_cc__Support_Category__r.maica_cc__Support_Purpose__c = 'Core'
                    WITH USER_MODE
            ];
            Decimal coreRemainingAmount = Utils.objects.defaultIfNull((Decimal) coreRemainingResults[0].get('Remaining_Amount__c'), 0);
            Set<Id> coreSupportCategories;
            if (coreRemainingAmount > 0) {
                coreSupportCategories = Utils.sObjects.getIdFieldValues([
                        SELECT maica_cc__Support_Category__c
                        FROM maica_cc__Funding_Item__c
                        WHERE maica_cc__Funding__c = :activePlanId AND maica_cc__Support_Category__r.maica_cc__Support_Purpose__c = 'Core'
                        WITH USER_MODE
                ], maica_cc__Funding_Item__c.maica_cc__Support_Category__c);
            }

            List<AggregateResult> remainingAmountSummary = [
                    SELECT SUM(maica_cc__Remaining_Amount__c) Remaining_Amount__c, maica_cc__Support_Category__c Support_Category__c
                    FROM maica_cc__Funding_Item__c
                    WHERE maica_cc__Funding__c = :activePlanId
                    WITH USER_MODE
                    GROUP BY maica_cc__Support_Category__c
                    HAVING SUM(maica_cc__Remaining_Amount__c) > 0
            ];

            for (AggregateResult result : remainingAmountSummary) {
                Decimal remainingAmount = (Decimal) result.get('Remaining_Amount__c');
                String categoryId = (String) result.get('Support_Category__c');
                if (remainingAmount > 0) {
                    categoryIds.add(categoryId);
                }
                remainingAmountBySupportCategory.put(categoryId, remainingAmount);
            }

            budgetMap = new Map<String, maica_cc__Funding_Item__c>();
            for (maica_cc__Funding_Item__c budgetVar : planBudgets) {
                Decimal remainingAmount = Utils.objects.defaultIfNull(remainingAmountBySupportCategory?.get(budgetVar.maica_cc__Support_Category__c), 0);

                if (coreSupportCategories != null && coreSupportCategories.contains(budgetVar.maica_cc__Support_Category__c) && budgetMap.containsKey(budgetVar.maica_cc__Support_Category__c) != true) {

                    for (Id coreSupportCategoryId : coreSupportCategories) {
                        if (budgetMap.containsKey(coreSupportCategoryId) != true) {
                            budgetMap.put(coreSupportCategoryId + '-' + budgetVar.maica_cc__Support_Item__c, budgetVar);
                            budgetMap.put(coreSupportCategoryId, budgetVar);
                        }
                    }

                } else if (remainingAmount > 0) {
                    budgetMap.put(budgetVar.maica_cc__Support_Category__c + '-' + budgetVar.maica_cc__Support_Item__c, budgetVar);
                    budgetMap.put(budgetVar.maica_cc__Support_Category__c, budgetVar);
                }
            }

            conditions.add('Product2.Support_Category__c IN :categoryIds');
        }

        queryFactory.setCondition(String.join(conditions, ' AND '));
        queryFactory.getOrderings().clear();
        queryFactory.addOrdering('Product2.Favourite__c', fflib_QueryFactory.SortOrder.DESCENDING, true);
        if (isCategoryProduct == true) {
            queryFactory.addOrdering('Product2.Category_Number__c', fflib_QueryFactory.SortOrder.ASCENDING, true);
        }
        queryFactory.addOrdering('Product2.Name', fflib_QueryFactory.SortOrder.ASCENDING);

        queryFactory.setLimit(this.limitVar + 1);

        String SOQL = queryFactory.toSOQL();
        SOQL = SOQL.replace('Product2.QuantityUnitOfMeasure', 'toLabel(Product2.QuantityUnitOfMeasure)');

        this.items = Database.query(SOQL);
        this.response.getMapper().mapFromListSObjects(
                'items',
                this.items,
                budgetMap == null ? null : new AutoMapper.BinderQueue(new PlanBudgetBinder(budgetMap, remainingAmountBySupportCategory)),
                this.limitVar
        );
    }

    class PlanBudgetBinder implements AutoMapper.IBinder {

        private Map<String, maica_cc__Funding_Item__c> budgetMap;
        private Map<String, Decimal> remainingAmountBySupportCategory;

        PlanBudgetBinder(Map<String, maica_cc__Funding_Item__c> budgetMap, Map<String, Decimal> remainingAmountBySupportCategory) {
            this.budgetMap = budgetMap;
            this.remainingAmountBySupportCategory = remainingAmountBySupportCategory;
        }

        public void bind(SObject record, Map<String, Object> dataMap) {
            PricebookEntry entryVar = (PricebookEntry) record;
            maica_cc__Funding_Item__c budgetVar = budgetMap.get(entryVar.Product2.Support_Category__c + '-' + entryVar.Product2Id);
            if (budgetVar == null) {
                budgetVar = budgetMap.get(entryVar.Product2.Support_Category__c);
            }
            dataMap.put('budget', budgetVar);
            dataMap.put('supportCategoryRemaining', remainingAmountBySupportCategory?.get(entryVar.Product2.Support_Category__c));
        }
    }
}