src/objects/maica_cc__Support_Category__c.object
<CustomObject>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agreement_End_Date__c</fullName>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>Represents how the funding is managed (based on the Funding Source).</description>
        <inlineHelpText>Represents how the funding is managed (based on the Funding Source).</inlineHelpText>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding_Source__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>maica_cc__Funding_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Represents the Funding for which this Service Agreement is being developed.</inlineHelpText>
        <label>Funding</label>
        <referenceTo>maica_cc__Funding__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Participant)</relationshipLabel>
        <relationshipName>Participant_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>maica_cc__Funding_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period_Type__c</fullName>
        <label>Period Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Plan</fullName>
                    <label>Active Plan Managed</label>
                </value>
                <value>
                    <fullName>Agreement</fullName>
                    <label>Service Agreement Managed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Schedule_Count__c</fullName>
        <label>Schedule Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_Day__c</fullName>
        <label>Schedule Day</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Day__c</fullName>
        <label>Service Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Frequency__c</fullName>
        <label>Service Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Day</fullName>
                    <label>Daily</label>
                </value>
                <value>
                    <fullName>Week</fullName>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>Month</fullName>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>One</fullName>
                    <label>One Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Time__c</fullName>
        <label>Service Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daytime</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Night</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <formula>PricebookEntry.Product2.Support_Category__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Support Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Item_Number__c</fullName>
        <formula>PricebookEntry.Product2.Support_Item_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Support Item Number</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>Indicates if the Product is the Bucket, or Category Level, Product for the related Support
            Category
        </description>
        <formula>Id = Support_Category__r.Category_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates if the Product is the Bucket, or Category Level, Product for the related Support
            Category
        </inlineHelpText>
        <label>Bucket</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Day__c</fullName>
        <label>Service Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Time__c</fullName>
        <label>Service Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daytime</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Night</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the Support Category associated with this Product.</description>
        <label>Support Category</label>
        <referenceTo>maica_cc__Support_Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Item_Number__c</fullName>
        <description>Unique NDIS Reference Number derived from Support Category, Sequence Number, Registration Group,
            Outcome Domain and Support Purpose
        </description>
        <externalId>true</externalId>
        <inlineHelpText>Unique NDIS Reference Number derived from Support Category, Sequence Number, Registration Group,
            Outcome Domain and Support Purpose
        </inlineHelpText>
        <label>Support Item Number</label>
        <length>55</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/NDISProductManagementQAMetaProc.cls
//SECURED!
@NamespaceAccessible
public with sharing class NDISProductManagementQAMetaProc extends MetadataProcessor {
    @NamespaceAccessible
    public override Response process(Request request) {
        this.request = request == null ? new MetadataProcessor.MetadataRequest() : (MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                OpportunityLineItem.Service_Frequency__c,
                OpportunityLineItem.Service_Day__c,
                OpportunityLineItem.Service_Time__c,
                OpportunityLineItem.Schedule_Day__c,
                OpportunityLineItem.Funding_Type__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private Opportunity oppVar;

    private void init() {

        String opportunityId = this.request.getRequiredString('recordId');

        oppVar = (Opportunity) Utils.arrays.firstOrException([
                SELECT Id, Participant__c, AccountId, Pricebook2Id, Funding__c, Agreement_Start_Date__c, Agreement_End_Date__c, Funding_Type__c
                FROM Opportunity
                WHERE Id = :opportunityId
                WITH USER_MODE
        ],
                'No Opportunity with Id: ' + opportunityId
        );
        this.response.put('opportunity', oppVar);
        this.response.put('isCombinationFunding', 'Combination'.equalsIgnoreCase(oppVar.Funding_Type__c));

        Utils.objects.throwIfBlank(oppVar.Pricebook2Id, 'Please assign the Pricebook to the Opportunity.');

        this.initPlanAndCategoriesTotalRemaining();

        List<OpportunityLineItem> items = [
                SELECT Id, Support_Category__c, Product2Id, Quantity, ListPrice, UnitPrice,
                        Product2.Id, Product2.Name, Product2.Support_Item_Number__c,
                        Product2.Support_Category__c, Product2.Support_Category__r.Name,
                        Product2.Support_Category__r.maica_cc__Support_Purpose__c, Product2.Bucket__c,
                        Start_Date__c, End_Date__c, Schedule_Count__c, Schedule_Day__c,
                        Service_Day__c, Service_Time__c, Period_Type__c,
                        TotalPrice, PricebookEntryId, Funding_Type__c
                FROM OpportunityLineItem
                WHERE OpportunityId = :opportunityId
                WITH USER_MODE
        ];

        this.response.put('items', items);

        this.response.selectOptions.put('periodTypeOptions', Utils.picklists.getPicklistValuesAsSelectOptions(OpportunityLineItem.Period_Type__c, new Set<String>{
                oppVar.Agreement_Start_Date__c == null || oppVar.Agreement_End_Date__c == null ? 'Agreement' : null,
                oppVar.Funding__c == null ? 'Plan' : null
        }));

        List<Structs.SelectOption> weekdayOptions = new List<Structs.SelectOption>{
                new Structs.SelectOption('Monday'),
                new Structs.SelectOption('Tuesday'),
                new Structs.SelectOption('Wednesday'),
                new Structs.SelectOption('Thursday'),
                new Structs.SelectOption('Friday')
        };

        List<Structs.SelectOption> serviceFrequencyWithoutPublicHolidayOptions = new List<Structs.SelectOption>{
                new Structs.SelectOption('Day', 'Daily'),
                new Structs.SelectOption('Week', 'Weekly'),
                new Structs.SelectOption('Month', 'Monthly'),
                new Structs.SelectOption('One', 'One Time')
        };

        List<Structs.SelectOption> serviceFrequencyWithoutDailyAndPublicHolidayOptions = new List<Structs.SelectOption>{
                new Structs.SelectOption('Week', 'Weekly'),
                new Structs.SelectOption('Month', 'Monthly'),
                new Structs.SelectOption('One', 'One Time')
        };

        this.response.selectOptions.put('weekdayOptions', weekdayOptions);
        this.response.selectOptions.put('serviceFrequencyWithoutPublicHolidayOptions', serviceFrequencyWithoutPublicHolidayOptions);
        this.response.selectOptions.put('serviceFrequencyWithoutDailyAndPublicHolidayOptions', serviceFrequencyWithoutDailyAndPublicHolidayOptions);
    }

    private void initPlanAndCategoriesTotalRemaining() {
        maica_cc__Funding__c activePlan = (maica_cc__Funding__c) Utils.arrays.firstOrNull([
                SELECT Id, Name, maica_cc__Participant__c, maica_cc__Last_NDIS_Sync__c, maica_cc__Start_Date__c, maica_cc__End_Date__c
                FROM maica_cc__Funding__c
                WHERE Id = :oppVar.Funding__c
                WITH USER_MODE
        ]);

        if (activePlan == null) {
            this.response.put('hasActivePlan', false);
            return;
        }

        if (oppVar.Participant__c != activePlan.maica_cc__Participant__c) {
            throw new Structs.ValidationException('Primary Contact on Opportunity is different to Participant on associated NDIS Plan');
        }

        List<maica_cc__Funding_Item__c> planBudgets = [
                SELECT Id, Name, maica_cc__Support_Category__c, maica_cc__Approved_Amount__c, maica_cc__Remaining_Amount__c
                FROM maica_cc__Funding_Item__c
                WHERE maica_cc__Funding__c = :activePlan.Id
                WITH USER_MODE
        ];
        Map<String, List<SObject>> budgetsByCategory = Utils.sObjects.getSObjectsListByAnyFieldMap(planBudgets, maica_cc__Funding_Item__c.maica_cc__Support_Category__c);

        List<AggregateResult> totals = [
                SELECT maica_cc__Support_Category__c Support_Category__c, SUM(maica_cc__Remaining_Amount__c) Remaining_Amount__c
                FROM maica_cc__Funding_Item__c
                WHERE maica_cc__Funding__c = :activePlan.Id
                WITH USER_MODE
                GROUP BY maica_cc__Support_Category__c
        ];
        Map<String, Decimal> totalRemainingByCategoryId = new Map<String, Decimal>();
        for (AggregateResult totalVar : totals) {
            totalRemainingByCategoryId.put((String) totalVar.get('Support_Category__c'), (Decimal) totalVar.get('Remaining_Amount__c'));
        }

        this.response.put('totalRemainingByCategoryId', totalRemainingByCategoryId);
        this.response.put('activePlan', activePlan);
        this.response.put('hasActivePlan', activePlan != null);
        this.response.put('activePlanStartDateFormatted', activePlan?.maica_cc__Start_Date__c?.format());
        this.response.put('activePlanEndDateFormatted', activePlan?.maica_cc__End_Date__c?.format());
        this.response.put('isEnforceActivePlan', activePlan != null);
        this.response.put('budgetsByCategory', budgetsByCategory);
        this.response.put('colorSetting.start', 20);
        this.response.put('colorSetting.end', 80);
    }
}